@startuml

class Personaje
class Cliente
class Pareja
class Mesera
class Jugador

class EstadoAnimoCliente
class EstatusCliente

class Restaurante
class Reloj
class Mesa
class Tele
class Patin
class Silla 
class Mostrador
class Basura
class Letrero
class Alfombra

class Pedido
class Platillo
class Pescado
class Camaron
class Nieve
class MalteadaFresa
class MalteadaVainilla

class CajaRegistradora
class Ahorro
class Propina
class MetaVenta
class VentaDiaria
class Perdida
class TotalVendido


@enduml
