@startuml

class Personaje
class Vida
class Escudo
class PorcentajeDanio
class Escenario
class Jugador
class Bot
class Ganador

class Ataque
class AtaqueNormal
class AtaqueAereo
class AtaqueEspecial
class Smash
class Agarre
class Combo
class EfectoAtaque

class Movimiento
class Salto
class Caida

class Mario
class Luigi
class DonkeyKong
class Samus
class Lucina
class Link
class Yoshi
class Kirby
class Zelda
class Pit
class Rosalina

Personaje *-- Vida
Personaje *-- Escudo
Personaje *-- PorcentajeDanio

Escenario *-- Personaje

Combo *-- Ataque

Jugador o-- Personaje
Personaje o-- Ataque
Personaje o-- Agarre
Personaje o-- Movimiento
Ataque o-- EfectoAtaque
Ganador o-- Jugador

Bot --|> Jugador

AtaqueNormal --|> Ataque
AtaqueAereo --|> Ataque
AtaqueEspecial --|> Ataque
Smash --|> Ataque

Salto --|> Movimiento
Caida --|> Movimiento

Mario --|> Personaje
Luigi --|> Personaje
DonkeyKong --|> Personaje
Samus --|> Personaje
Lucina --|> Personaje
Link --|> Personaje
Yoshi --|> Personaje
Kirby --|> Personaje
Zelda --|> Personaje
Pit --|> Personaje
Rosalina --|> Personaje

@enduml
