@startuml PenguinDinner

class Personaje
class Cliente
class Pareja
class Mesera
class Jugador

Cliente --|> Personaje
Mesera --|> Personaje
Pareja --|> Cliente

Jugador "1" o-- "1" Mesera


class EstadoAnimoCliente
class EstatusCliente

Cliente "1" *-- "1" EstadoAnimoCliente
Cliente "1" *-- "1" EstatusCliente

class Restaurante
class Reloj
class Mesa
class Tele
class Patin
class Silla
class Mostrador
class Basura
class Letrero
class Alfombra
class CajaRegistradora

Restaurante "1" *-- "1" Reloj
Restaurante "1" *-- "1..*" Mesa
Restaurante "1" *-- "0..*" Tele
Restaurante "1" *-- "1..*" Silla
Restaurante "1" *-- "1" Mostrador
Restaurante "1" *-- "1" CajaRegistradora
Restaurante "1" *-- "0..1" Letrero
Restaurante "1" *-- "0..*" Alfombra
Restaurante "1" *-- "1" Basura

Mesa "1" *-- "2" Silla

Mesera "1" o-- "0..1" Patin
Cliente "1" o-- "0..1" Mesa
Mesera "1" o-- "1" Mostrador
Mesera "1" o-- "1" Basura

class Pedido
class Platillo
class Pescado
class Camaron
class Nieve
class MalteadaFresa
class Sopa

Cliente "1" *-- "0..*" Pedido
Mesera "1" o-- "0..*" Pedido
Pedido "1" *-- "1..*" Platillo

Pescado --|> Platillo
Camaron --|> Platillo
Nieve --|> Platillo
MalteadaFresa --|> Platillo
Sopa --|> Platillo

class Ahorro
class Propina
class MetaVentaDiaria
class VentaDiaria
class Perdida
class TotalVendido

CajaRegistradora "1" *-- "1" Ahorro
CajaRegistradora "1" *-- "1" MetaVentaDiaria
CajaRegistradora "1" *-- "1" VentaDiaria
CajaRegistradora "1" o-- "1" Propina
CajaRegistradora "1" *-- "1" TotalVendido

Cliente "1" o-- "1" Propina
Basura "1" *-- "0..*" Perdida

@enduml